#!/usr/bin/env python
'''%s: Convert text to IPA.

USAGE:  t2ipa <languagename> <inputfile> <outputfile>
Convert text in <inputfile> (default: sys.stdin) into IPA, using the rules for <languagename>.
Write to <outputfile> (default: sys.stdout).
'''
import sys
import text2ipa

if len(sys.argv)<2:
    sys.exit(__doc__%(sys.argv[0]))

# Language name must be first input
converter = text2ipa.Converter(sys.argv[1])

# Read the input
if len(sys.argv) >= 3:
    with open(sys.argv[2]) as f:
        itext = f.read()
else:
    with sys.stdin as f:
        itext = f.read()

# Convert
otext = converter.convert(itext)

# Print to output
if len(sys.argv) >= 4:
    with open(sys.argv[3],'w') as f:
        f.write(otext)
else:
    print(otext)




